name: dapackage_example
description: Example code for the dapackage library.
version: 1.0.0
author: Mauricio Togneri <mauricio.togneri@gmail.com>
homepage: https://github.com/mauriciotogneri/dapackage

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter
  
  yaml: ^2.1.11
  http: ^0.12.0+2